doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '17.0'

    orm:
        mappings:
            Order:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine'
                prefix: 'App\Domain\Order'
                alias: Order
