services:
  base:
    image: tag-base:latest
    build:
      context: ./
      dockerfile: ./docker/base/Dockerfile
  application:
    depends_on:
      - base
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    image: tag-api:latest
    volumes:
      - ./docker/dev/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/home/www
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: postgresql://main:main@database:5432/main?sslmode=disable
      ADMIN_PANEL_TOKEN: ${ADMIN_PANEL_TOKEN}
      TZ: Europe/Warsaw
    networks:
      - default
    ports:
      - "8000:80"
  worker:
    depends_on:
      - base
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    image: tag-api:latest
    volumes:
      - ./docker/dev/vhost.conf:/etc/apache2/sites-enabled/000-default.conf
      - .:/home/www
    environment:
      APP_ENV: dev
      APP_DEBUG: "1"
      DATABASE_URL: postgresql://main:main@database:5432/main?sslmode=disable
      ADMIN_PANEL_TOKEN: ${ADMIN_PANEL_TOKEN}
      TZ: Europe/Warsaw
    command: ["php", "/home/www/bin/console", "messenger:consume", "async", "-vv"]
    networks:
      - default
    restart: unless-stopped
  database:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - tag-postgresql:/var/lib/postgresql/data
volumes:
  tag-postgresql:
    external: true
